name: Push components to Espressif Component Service

on:
  push:
    tags:
      - 'v*'

jobs:
  upload_components:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Upload components to component service
        uses: espressif/upload-components-ci-action@v2
        with:
          name: "micropython-helper"
          namespace: "TomasWeij"
          api_token: ${{ secrets.ESP_COMPONENTS_TOKEN }}
